/*
 * Write CPU here
*/

#include"mem.c"

/*Arithmetic operation section*/
RASM_BOOL RASM_ADD(RASM_MOV_PACK,RASM_MOV_PACK);
RASM_BOOL RASM_SUB(RASM_MOV_PACK,RASM_MOV_PACK);
RASM_BOOL RASM_MUL(RASM_MOV_PACK,RASM_MOV_PACK);
RASM_BOOL RASM_DIV(RASM_MOV_PACK,RASM_MOV_PACK);
RASM_BOOL RASM_UADD(RASM_MOV_PACK,RASM_MOV_PACK);
RASM_BOOL RASM_USUB(RASM_MOV_PACK,RASM_MOV_PACK);
RASM_BOOL RASM_UMUL(RASM_MOV_PACK,RASM_MOV_PACK);
RASM_BOOL RASM_UDIV(RASM_MOV_PACK,RASM_MOV_PACK);
/*Logical operation section*/
RASM_BOOL RASM_OR(RASM_MOV_PACK,RASM_MOV_PACK);
RASM_BOOL RASM_AND(RASM_MOV_PACK,RASM_MOV_PACK);
RASM_BOOL RASM_NOT(RASM_MOV_PACK,RASM_MOV_PACK);
RASM_BOOL RASM_XOR(RASM_MOV_PACK,RASM_MOV_PACK);
RASM_BOOL RASM_SAL(RASM_MOV_PACK,RASM_MOV_PACK);
RASM_BOOL RASM_SAR(RASM_MOV_PACK,RASM_MOV_PACK);
RASM_BOOL RASM_SHL(RASM_MOV_PACK,RASM_MOV_PACK);
RASM_BOOL RASM_SHR(RASM_MOV_PACK,RASM_MOV_PACK);
RASM_BOOL RASM_CMP(RASM_MOV_PACK,RASM_MOV_PACK);
/*Oh my god!I need to write so many function!!*/
